FROM debian:{{ VERSION }} as build
RUN export DEBIAN_FRONTEND=noninteractive; \
    export DEBCONF_NONINTERACTIVE_SEEN=true; \
    apt-get update && apt-get -y upgrade && \
    apt-get install -y clang git build-essential curl
WORKDIR /app
RUN git clone https://github.com/nodejs/node -b v{{ NODE_VERSION }}
WORKDIR /app/node

{{#if (eq NO_DETECT_LEAKS 'true')}}
ENV ASAN_OPTIONS=detect_leaks=0
{{/if}}

{{#if (eq DEBUG 'true')}}
RUN CC=$(which clang) CXX=$(which clang++) ./configure --debug --enable-asan
{{else}}
RUN CC=$(which clang) CXX=$(which clang++) ./configure --enable-asan
{{/if}}
    
RUN CC=$(which clang) CXX=$(which clang++) make -j3

RUN mkdir -p /nodejs/node
{{#if (eq DEBUG 'true')}}
RUN mv /app/node/out/Debug/node /nodejs/node/node
{{else}}
RUN mv /app/node/out/Release/node /nodejs/node/node
{{/if}}
RUN curl -qL https://www.npmjs.com/install.sh | \
    PATH="$PATH:/nodejs/node" sh && \
    mv /nodejs/bin /nodejs/npm
ENV PATH="$PATH:/nodejs/node:/nodejs/npm"
RUN node --version
RUN npm --version

FROM debian:{{ VERSION }}-slim

RUN apt-get update && apt-get install -y libatomic1
COPY --from=build /nodejs /nodejs
ENV PATH="$PATH:/nodejs/node:/nodejs/npm"

CMD [ "/bin/bash" ]
